sudo: required
services:
  - docker

before_install:
  - docker build -t adamjmeyer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adamjmeyer/react-test npm test

after_success:
  - docker build -t adamjmeyer/multi-client ./client
  - docker build -t adamjmeyer/multi-nginx ./nginx
  - docker build -t adamjmeyer/multi-server ./server
  - docker build -t adamjmeyer/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push meyeradamj/multi-client
  - docker push meyeradamj/multi-nginx
  - docker push meyeradamj/multi-server
  - docker push meyeradamj/multi-worker

deploy:
  edge: true # missing bucket_name error
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udemy-docker-complex"
  env: "UdemyDockerComplex-env"
  bucket_name: "elasticbeanstalk-us-east-2-399713599643"
  bucket_path: "udemy-docker-complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
